services:
  - type: web
    name: TestReverseProxyRender
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
